### ISSUE TITLE
useRStyle is not working on orientation change.

### ISSUE THREAD

**Issue by gozegotushar** [Mhp23/react-native-full-responsive#4]
i tried using given example of useRStyle while performing orientation change but it is not working.
my expectation is rw(90) should take 90% width of device in any orientation.

https://github.com/user-attachments/assets/2bf7dfa2-54de-445d-a73f-ec255fefe867

```
import * as React from 'react';
import { View, Text, useWindowDimensions } from 'react-native';
import { FRProvider, useRStyle, rw } from 'react-native-full-responsive';

const SIZE = 20;

const ResponsiveBox: React.FC = () => {

  const SCREEN_WIDTH = useWindowDimensions().width;
  const SCREEN_HEIGHT = useWindowDimensions().height;

  const isLandscapeMode = SCREEN_WIDTH > SCREEN_HEIGHT;

  const styles = useRStyle({
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    box: {
      backgroundColor: 'yellow',
      marginVertical: `${SIZE}rs`,
      width:rw(90),
    },
    textBold: {
      fontWeight: 'bold',
      fontSize: 30,
    },
  },[isLandscapeMode],'recursive');

  return (
    <View style={styles.container}>
      <View style={styles.box}>
        <Text style={styles.textBold}>{isLandscapeMode ? 'Landscape' : 'Potrait'}</Text>
        <Text style={styles.textBold}>My awesome responsive text!</Text>
      </View>
    </View>
  );
};

export default function App() {
  return (
    <FRProvider type="md">
      <ResponsiveBox />
    </FRProvider>
  );
}

```

**Comment by Mhp23** [comment]
@gozegotushar Hi, if you want to use the responsive width method (rw) and re-measure sizes when the orientation changes, don’t handle it manually. Let `useRStyle` handle the dimension change event. You only need to do the following:

```tsx
import * as React from 'react';
import { View, Text, useWindowDimensions } from 'react-native';
import { FRProvider, useRStyle, rw } from 'react-native-full-responsive';

const SIZE = 20;

const ResponsiveBox: React.FC = () => {
  const SCREEN_WIDTH = useWindowDimensions().width;
  const SCREEN_HEIGHT = useWindowDimensions().height;

  const isLandscapeMode = SCREEN_WIDTH > SCREEN_HEIGHT;
 
 //the default style parsing method for the third argument is recursive
  const styles = useRStyle({
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    box: {
      backgroundColor: 'yellow',
      marginVertical: `${SIZE}rs`,
      width: '90rw', //<-- here
    },
    textBold: {
      fontWeight: 'bold',
      fontSize: 30,
    },
  }, []);

  return (
    <View style={styles.container}>
      <View style={styles.box}>
        <Text style={styles.textBold}>{isLandscapeMode ? 'Landscape' : 'Potrait'}</Text>
        <Text style={styles.textBold}>My awesome responsive text!</Text>
      </View>
    </View>
  );
};

export default function App() {
  return (
    <FRProvider type="md">
      <ResponsiveBox />
    </FRProvider>
  );
}
``` 

However, when using the responsive width method, the method will use the initially bundled device width. For custom widths, you can pass the desired width as the second argument for calculation:

`rw(SIZE, CUSTOM_WIDTH)`

[rw docs](https://github.com/Mhp23/react-native-full-responsive/blob/main/USAGE.md#responsivewidth-rw)
[useRStyle docs](https://github.com/Mhp23/react-native-full-responsive/blob/main/USAGE.md#userstyle)
[createRStyle docs](https://github.com/Mhp23/react-native-full-responsive/blob/main/USAGE.md#createrstyle)

**Comment by gozegotushar** [comment]
@Mhp23  is there any better way to provide style file to useRStyle hook, if style goes big component can become clumsy.

**Comment by Mhp23** [comment]
@gozegotushar as a best practice, splitting up your styles might be helpful. For example:

- if some styles are consistent across multiple components, define them as global styles and reuse them (like the container style mentioned above).
- use `useRStyle` only for components or places where it’s necessary (such as dynamic styles or when styles need to change based on dimensions). Otherwise, use `createRStyle`, similar to RN StyleSheet.create API
